spring.application.name=inventory-backend

# Database
spring.datasource.url=jdbc:mysql://sql7.freesqldatabase.com:3306/sql7819828?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=sql7819828
spring.datasource.password=8UApVRK3Qp

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=inventory_super_secret_key_2026_dipesh_patel
jwt.expiration=86400000